import { WorkSkillId } from './WorkSkill';

export enum TechType {
  BuildTool = 'Build Tool',
  CoreTechnology = 'Core Technology',
  CSSFramework = 'CSS Framework',
  Database = 'Database',
  DataManagement = 'Data Management',
  Framework = 'Framework',
  GraphicsAPI = 'Graphics API',
  Infrastructure = 'Infrastructure',
  Language = 'Language',
  Methodology = 'Methodology',
  Pattern = 'Pattern',
  Practice = 'Practice',
  Role = 'Role',
  SoftSkill = 'Soft Skill',
  StateManagement = 'State Management',
  Tool = 'Tool',
  UILibrary = 'UI Library',
  VersionControl = 'Version Control',
}

// Technology type classifications
export const techTypes: Record<WorkSkillId, TechType> = {
  [WorkSkillId.AgileScrum]: TechType.Methodology,
  [WorkSkillId.Angular]: TechType.Framework,
  [WorkSkillId.Architecture]: TechType.Practice,
  [WorkSkillId.C]: TechType.Language,
  [WorkSkillId.ChakraUI]: TechType.UILibrary,
  [WorkSkillId.CICD]: TechType.Practice,
  [WorkSkillId.CodeOptimization]: TechType.Practice,
  [WorkSkillId.CodeReview]: TechType.Practice,
  [WorkSkillId.ColdFusion]: TechType.Framework,
  [WorkSkillId.ContextAPI]: TechType.StateManagement,
  [WorkSkillId.CPlusPlus]: TechType.Language,
  [WorkSkillId.CSharp]: TechType.Language,
  [WorkSkillId.Dart]: TechType.Language,
  [WorkSkillId.DependencyInjection]: TechType.Pattern,
  [WorkSkillId.Flutter]: TechType.Framework,
  [WorkSkillId.Git]: TechType.VersionControl,
  [WorkSkillId.HTML5CSS3]: TechType.CoreTechnology,
  [WorkSkillId.InversionOfControl]: TechType.Pattern,
  [WorkSkillId.Java]: TechType.Language,
  [WorkSkillId.JavaScript]: TechType.Language,
  [WorkSkillId.Mentoring]: TechType.SoftSkill,
  [WorkSkillId.MicrosoftSQLServer]: TechType.Database,
  [WorkSkillId.NextJs]: TechType.Framework,
  [WorkSkillId.NgrxStore]: TechType.StateManagement,
  [WorkSkillId.OpenGL]: TechType.GraphicsAPI,
  [WorkSkillId.ProjectPlanning]: TechType.SoftSkill,
  [WorkSkillId.React]: TechType.Framework,
  [WorkSkillId.ReactQuery]: TechType.DataManagement,
  [WorkSkillId.Redux]: TechType.StateManagement,
  [WorkSkillId.ResponsiveDesign]: TechType.Practice,
  [WorkSkillId.SAFe]: TechType.Methodology,
  [WorkSkillId.ScrumMaster]: TechType.Role,
  [WorkSkillId.SEO]: TechType.Practice,
  [WorkSkillId.SpringBoot]: TechType.Framework,
  [WorkSkillId.SpringMVC]: TechType.Framework,
  [WorkSkillId.SQL]: TechType.Language,
  [WorkSkillId.TailwindCSS]: TechType.CSSFramework,
  [WorkSkillId.TDD]: TechType.Practice,
  [WorkSkillId.TechnicalLeadership]: TechType.SoftSkill,
  [WorkSkillId.TechnicalWriting]: TechType.Practice,
  [WorkSkillId.Testing]: TechType.Practice,
  [WorkSkillId.TypeScript]: TechType.Language,
  [WorkSkillId.VersionOne]: TechType.Tool,
  [WorkSkillId.VMWare]: TechType.Infrastructure,
  [WorkSkillId.Webpack]: TechType.BuildTool,
};

// Color scheme for technology types
export const typeColors: Record<TechType, string> = {
  [TechType.BuildTool]: 'bg-amber-50 text-amber-600',
  [TechType.CoreTechnology]: 'bg-gray-50 text-gray-600',
  [TechType.CSSFramework]: 'bg-pink-50 text-pink-600',
  [TechType.Database]: 'bg-cyan-50 text-cyan-600',
  [TechType.DataManagement]: 'bg-indigo-50 text-indigo-600',
  [TechType.Framework]: 'bg-blue-50 text-blue-600',
  [TechType.GraphicsAPI]: 'bg-rose-50 text-rose-600',
  [TechType.Infrastructure]: 'bg-slate-50 text-slate-600',
  [TechType.Language]: 'bg-purple-50 text-purple-600',
  [TechType.Methodology]: 'bg-teal-50 text-teal-600',
  [TechType.Pattern]: 'bg-violet-50 text-violet-600',
  [TechType.Practice]: 'bg-emerald-50 text-emerald-600',
  [TechType.Role]: 'bg-teal-50 text-teal-600',
  [TechType.SoftSkill]: 'bg-sky-50 text-sky-600',
  [TechType.StateManagement]: 'bg-indigo-50 text-indigo-600',
  [TechType.Tool]: 'bg-zinc-50 text-zinc-600',
  [TechType.UILibrary]: 'bg-pink-50 text-pink-600',
  [TechType.VersionControl]: 'bg-orange-50 text-orange-600',
};
